Refactor
fac/visual_regression_predictor pull request #13
Opened 2023-07-26 10:34 UTC by dmorgan-fa

2023-08-15 10:55 UTC, singhprd requested changes
A few thoughts - just as notes because it be great to chat:

This looks great - nice separation of concerns, testing, idiomatic and specs! All the good stuff that makes it easy to work on going forwards. Nice work 🚀 

A few thoughts/discussion points:
- Should the artifacts be committed to the repo and be the default option if the artifacts_dir isn't specified? Won't these just drift out of date? Better to just leave them out?
- It's mostly great, but in a few places - mostly runner.rb - there is a mixing of the logic (working out the list of PR) and the presenter (printing to stdout/file ect). That leads to some clumsy code that is harder to read I think. I think it'd be better to have one class that works out an array of data, then another that takes an array of data and puts it in a message. That's also good long term because if you ever need another format, just create another presenter type class 👍 I think it might also naturally improve clumsy method names like `write_message_and_std_out`.
- could the two modes be separate classes too - it makes runner.rb harder to follow? A BasePredictor then a BranchPredictor and DailySummaryPredictor might separate things nicely?

- In general I think there is a fair few things that would fall under the category of the YAGNI principle ("You Aren't Gonna Need It"). i.e. the only production use case of this is calling it in an action with a limited set of input options, so I wouldn't say there is a need for things like `auth_token_from_gh`, or even things like having CLI options at all. Things like hard-coding the paths, using ENV vars for the few options that might be needed might make things dramatically simpler. Simpler means less code, easier to read/update, less to go wrong ect. If a new requirement comes along later it's can always be added then! I think a lot of it comes from local testing, but I don't think that needs to seep into the production code if it adds to the complexity - eg just use GITHUB_ACCESS_TOKEN=$(#token) bin/visual_regression_predictor when testing, rather than adding the code for `auth_token_from_gh`?

- for review we could do the artifact changes then the real code changes to make it easier?

2023-08-15 10:58 UTC, singhprd commented on lib/visual_regression_predictor/block_list.rb
> +  # A global BlockList used to filter out common files that would otherwise raise a lot of flase positives due
```suggestion
  # A global BlockList used to filter out common files that would otherwise raise a lot of false positives due
```

2023-08-15 11:02 UTC, singhprd commented on lib/visual_regression_predictor/runner.rb
> +      @message_file_path ||= "#{VisualRegressionPredictor.root_path}/messages/message-#{timestamp.gsub(/ |:/, "-")}"
Can the `timestamp.gsub` shenanigans can be avoided by setting the `strftime` as you're wanting it:

```ruby
timestamp = DateTime.now.strftime("%Y-%m-%d-%H-%M-%S")
```

2023-08-15 12:19 UTC, singhprd approved these changes

2023-08-15 13:45 UTC, singhprd approved these changes
Nice one, looks good to me 👍

2023-08-15 13:45 UTC, singhprd approved these changes
Nice one, looks good to me 👍

2023-08-15 13:54 UTC, dmorgan-fa commented
Thanks for the feedback and chat @singhprd 🙏 
I've raised a few tickets to track some of the suggestions/discussion we had:
- https://github.com/fac/visual_regression_predictor/issues/16
- https://github.com/fac/visual_regression_predictor/issues/17
- https://github.com/fac/visual_regression_predictor/issues/18

Please feel free to add any extra context if I've missed it, or shout if there's something I've overlooked.

2023-08-16 09:14 UTC, singhprd approved these changes

2023-08-16 12:12 UTC, merged